### ISSUE TITLE
No license assigned to your code

### ISSUE THREAD

**Issue by jryberg** [jubicoy/phplist-docker#1]
Hi,

I would like to use your work as a base for my own version but you don't have any license. 

That makes it hard since nobody actually are allowed to use, share or modify anything you created. 
https://choosealicense.com/no-license/

Would you please add a license?   =)

**Comment by jesseik** [comment]
Thanks for pointing this out! Added MIT license in baff8bc6739ce3e6470f8a9f0f9d90971fa6ef9c
