### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by digitalkram** [jubicoy/phplist-docker#4]
Hi there

Small doc error. Readme shows that you configure DB connection via DB_* env vars but entrypoint.sh actually uses MYSQL_* and DB_PASS = MYSQL_PASSWORD and DB_NAME = MYSQL_DATABASE

Cheers

**Comment by jesseik** [comment]
Thanks for pointing this out. Updated README with 5ea147b8ebf7dce512982d0c6d976a485336cda1
